Description: >
    Sean Breach / Udacity - Capstone Project
    This template deploys a Ubuntu Dev Box

Parameters:
    EnvironmentName:
        Default: CapstoneEnvName
        Description: This the Environment Name for the Capstone Project
        Type: AWS::SSM::Parameter::Value<String>

Resources:
    # App Server Setup Here
    UbuntuDevInstance:
      Properties:
        BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: '8'
        InstanceType: t2.micro
        ImageId: ami-09dd2e08d601bff67
        KeyName: "SBUdacityKP"
        SecurityGroupIds: 
          - "sg-01453636891ec4e19"
        SubnetId: "subnet-00630b20848b54040"
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            #--Setup Server--
            apt-get update -y
            # Python 3 - Required for Boto
            apt install python3-pip -y
            # Docker Setup
            apt install docker.io -y
            apt-get update
      Type: AWS::EC2::Instance

Outputs: 
    EC2InstanceIP: 
        Description: A reference to the created EC2 IP
        Export:
          Name: !Sub ${EnvironmentName}-UbuntuDevInstanceID
        Value: !GetAtt UbuntuDevInstance.PublicIp